### PR TITLE
Translate in Italian language!

### PR DESCRIPTION
**Pull request by Denisov21**
translate in Italian language!

### CODE REVIEW

**Comment by Liongold** [comment]
@Denisov21 Do you mind if I don't merge this for now? I have a couple of other strings to add to the extension. I'll tell you when I did them so that you can update the file, if it isn't a problem for you.

**Comment by Denisov21** [comment]
@Liongold Okay expects to merge!

**Comment by Liongold** [comment]
@Denisov21 Could you add an entry for italian in src/nls/strings.js, please? That way, the whole change will be merged in one go. Sorry if I'm asking too much.

**Comment by Denisov21** [comment]
@Liongold Yes, done! I think you can merge it! I will update the translation later if necessary!

**Comment by Liongold** [comment]
@Denisov21 Grazie mille per la tua contribuzione. And I hope that my small Italian knowledge arrives until this sentence.

**Pull request merged**
